Repository melaniesigrid/catalog-of-things, pull requests merged in 2022-04, with the labels that each got.

#25 Group Tasks
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .gitignore
  .rubocop.yml
  lib/app.rb
  lib/item.rb
  main.rb
Labels: enhancement

#28 Add Book and Label classes
  lib/book.rb
  lib/label.rb
Labels: enhancement

#29 Store Music Data
  lib/item.rb
  lib/music/genre.rb
  lib/music/music_album.rb
  lib/music/music_helpers.rb
  lib/music/music_menu.rb
Labels: enhancement

#32 Tests for Game and Author classes
  spec/author_spec.rb
  spec/authors.json
  spec/game_spec.rb
  spec/games.json
Labels: Testing

#35 Add tests for MusicAlbum and Genre classes
  spec/authors.json
  spec/games.json
  spec/genre_spec.rb
  spec/music_album_spec.rb
Labels: Testing

#37 Game and Author SQL tables
  schema.sql
Labels: enhancement

#33 Create book menu and helpers with methods
  lib/app.rb
  lib/book.rb
  lib/books/book.rb
  lib/books/book_menu.rb
  lib/books/label.rb
  music.json
Labels: enhancement

#38 Add music_album and genre tables to schema
  schema.sql
Labels: enhancement

#39 Update README.md
  README.md
  catalog_of_my_things.png
Labels: documentation

#40 Add tests for label and books
  books.json
  lib/app.rb
  lib/books/book_menu.rb
  lib/game/game_helpers.rb
  music.json
  schema.sql
  spec/authors.json
  spec/book_spec.rb
  spec/books.json
  spec/games.json
  spec/label_spec.rb
  spec/labels.json
Labels: Testing
